### ISSUE TITLE
Default validator should be `allowAny` even when field has a `factory` on its schema

### ISSUE THREAD

**Issue by hbarcelos** [hbarcelos/speckoloo#2]
@sauloxd I believe the way we defined the default validator it's wrong.

We defined that any field with a `factory` attribute would be considered a nested entity and its default validator would delegate the validation to that entity by calling `validate` on it

However, I believe this assumption is too strong. Sometimes we might want to use a factory just to perform a data transformation, not turning it into an entity itself.

Consider the following schema:

```javascript
const mySchema = {
  field1: {
    factory: String //  `field1` must be a string, not an entity
  },
  childEntity: {
    factory: SomeEntityFactory // `childEntity` is indeed a nested entity
  }
}
```

I think we have 2 options here:

1. Create yet another attribute on schema definition, something like a `isEntity` flag:

```javascript
const mySchema = {
  field1: {
    factory: String //  `field1` must be a string, not an entity
  },
  childEntity: {
    factory: SomeEntityFactory, // `childEntity` is indeed a nested entity,
    isEntity: true
  }
}
```

2. Export the default `delegate` validator and use it wherever a nested entity is present:

```javascript
import defaultValidators from 'speckoloo'
const { delegate } = defaultValidators

const mySchema = {
  field1: {
    factory: String //  `field1` must be a string, not an entity
  },
  childEntity: {
    factory: SomeEntityFactory, // `childEntity` is indeed a nested entity,
    validator: delegate
  }
}
```

I believe option **#2** is better, because it doesn't bloat the schema definition interface.

What do you think?

**Comment by Sauloxd** [comment]
Hmm, I agree! Let's do the delegate option then.
Let's just not forget to document every use-case and schema configuration for our factory, so our users won't assume and/or forget to delegate the validator to entity or anything like that!

I'll work on the readme as an exercise to see if the api's interface is good enough!

**Comment by hbarcelos** [comment]
Done!
